import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import client from "../../apollo-client";
import Link from "next/link";
import { getProductsQuery } from "../../utils";
import HeaderLinks from "../../components/HeaderLinks";

export default function Home({ products }) {
  const firstVariant = (product) => {
    return (product.variants || [])[0].id;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Cart Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeaderLinks />

        <h1>Products List</h1>

        <div className={styles.grid}>
          {products.map((product) => (
            <div key={product.title} className={styles.card}>
              <Link
                href={`/products/${encodeURIComponent(
                  product.id
                )}/${encodeURIComponent(firstVariant(product))}`}
              >
                <div>
                  <Image
                    src={product.thumbnail}
                    alt={product.title}
                    width={500}
                    height={500}
                  />
                  <p>
                    {product.brand} - {product.title}
                  </p>
                </div>
              </Link>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>Author: Umesh Mahato</footer>
    </div>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query({ query: getProductsQuery });

  return {
    props: {
      products: data.getProducts.slice(0, 30),
    },
  };
}
