import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cart Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* This page will not be rendered. */}
      <main className={styles.main}>
        <h1 className={styles.title}>Entry Page</h1>
      </main>
      <footer className={styles.footer}>Author: Umesh Mahato</footer>
    </div>
  );
}
